### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by popey** [bmx-ng/bmx-site#10]
The letsencrypt ssl cert for blitzmax.org expired an hour ago. 

![image](https://user-images.githubusercontent.com/1841272/50991150-ddb59800-150b-11e9-8012-acf538a44b5a.png)

**Comment by GWRon** [comment]
The auto-cert bot might need some additional params to update properly (hangs on my server from time to time too).

Good spot.

**Comment by woollybah** [comment]
Thanks for the heads-up.
I've been having issues with auto-renewal. Hopefully it will work properly next time
