### ISSUE TITLE
[Language] Functions missing example

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bmx-site#11]
The text mentions an example, which is missing.

We may also want to add more stuff here about things such as `Export` and `{ nomangle }` options - linking to appropriate other sections as required.

**Comment by GWRon** [comment]
Yes it also needs to link to a short tutorial on writing and interacting with shared libraries.

The differences of stdcall and win32 should be explained in 2-3 sentences too.

**Comment by woollybah** [comment]
stdcall and win32 are the same :-)

**Comment by GWRon** [comment]
You are right.

It might need a small snippet/doc for using external stuff:

- Dlls (with cdecl and stdcall differences)
- c files
