### ISSUE TITLE
Add hooks to commits

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-site#3]
If you commit something to the bmx-site repo the website should automagically update.

https://developer.github.com/v3/activity/events/types/#pushevent

So you route it to a script which updates the website-content accordingly (or recreates stuff there).

**Comment by woollybah** [comment]
Hah hah... yeah, so I'll need docker or something running with an instance of docusaurus ready to process the updates, then have the generated content magically ftp'd onto the website?

**Comment by GWRon** [comment]
They (docusaurus) seem to have a "docker"-portion in their documentation.

You might aswell install "node" on your server (without exposing it to an externally available port).

But it does not matter "how" you do it. Just use the webhook to inform your "create static website"-toolchain to do something.

So a simple process would be:
- script blitzmaxdomain.tld/website_onbmxsiteupdate.php
- script gets called via webhook
- script checks latest revision hash versus locally stored "latest hash" (to avoid misuse-ability) and fetches stuff from github
- script executes your docusaurus installation to update its static content from the .md files you just fetched **
- copy the generated docusaurus output to your blitzmaxdomain.tld/public/html-whatsoever folder

** this depends on how the "transformation" is done.

**Comment by woollybah** [comment]
Well, it only took four days to get it working... :-p

**Comment by GWRon** [comment]
See how easy it is. Compare how long it took to become father :-)
