### ISSUE TITLE
Adding Discord-chat-links

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-site#38]
Uploading the image to here allows to directly use it on the website.

![613699895139762176](https://user-images.githubusercontent.com/2625226/75874548-3d5abb00-5e12-11ea-9142-6ae9bae79f5b.png)

![613699895139762176 (1)](https://user-images.githubusercontent.com/2625226/75874927-076a0680-5e13-11ea-9c63-5de88624df6d.png)

I would like to add a chat-link to the website displaying current amount of users - similar to the github stars.

**Comment by GWRon** [comment]
I propsed it via a Pull-Request but to make it complete I post it here too:

```
            <a
              href="https://discord.gg/udSSJkj"
              target="_blank"
              rel="noreferrer noopener">
              <img src="https://user-images.githubusercontent.com/2625226/75874927-076a0680-5e13-11ea-9c63-5de88624df6d.png"
                   alt="Chat on Discord"
                   data-canonical-src="https://img.shields.io/discord/613699895139762176.svg?logo=discord&color=DDDDDD&logoColor=555555&style=social" style="max-width:100%;"
              >
            </a>
```

**Comment by woollybah** [comment]
So, something like this then...
```
<a href="https://discord.gg/udSSJkj" target="_blank" rel="noreferrer noopener">
    <img alt="Discord" src="https://img.shields.io/discord/613699895139762176?logo=discord&style=social"/>
</a>
```

**Comment by GWRon** [comment]
Yes ... but the link there is using a PNG as default and the canonical url is the actual url to use (an svg)
