### ISSUE TITLE
Increase spacing between functions in API

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-site#8]
For now there seems to be a bit "too little" space between the function listings in the API section of the website.

Especially with the "dark background" of the code example boxes this leads to a bit of "shift" on what is important on the website and where a new section starts.

![img](http://i.imgur.com/jG1TZDs.png)

For now it looks like
```
Example
- code box
- function ref
- description
```

It should look as if it was
```
Function ref
- description
- example code box
```

Having the function reference line similar to a "codebox" is nice but somehow it lacks "importance" or "header"-like-behaviour (section header).

**Comment by GWRon** [comment]
the function reference is even a bit "indented" compared to the example code box. This makes it even "less important".

Another thing is "returns" being nearly equal sized to the "function reference" (which acts - as said - as a header for each function). This means it becomes harder to distinguish between "child sections" (description, returns, example) and "section" (the function reference code box).

![img](http://i.imgur.com/Kx5YDgm.png)

**Comment by GWRon** [comment]
There are some solutions to these problems:

- create a padding-bottom to each section (maybe about "3 lines of text" high)
- use a "<hr />"-like element (horizontal ruler) to split apart individual functions - might look a bit "too much" if you only have "function ref" + 1line-desc and no example box, also might have a bit too much contrast to potentially existing example code boxes -> only use the "<hr />" as a neglictable guidance (light gray or so)
- use different font sizes -> big function references might look odd if they are too long (and become multiline)
- use some kind of "bullet" before the function ref - as a kind of section mark, maybe a light rocket? Here same problems for "short paragraphs" (function ref + 1line desc), might look a bit "too much".


Any thoughts / additional ideas? If desired I could come up with some mockups

**Comment by woollybah** [comment]
Some functions are already long, so I don't think making them larger will help much.

Padding might help.

Maybe the big black code boxes are too big and black? (black fits with the general theme of the site, though)

**Comment by woollybah** [comment]
Could probably add a couple of ```<br/>``` at the bottom of a section, which might improve things.

**Comment by GWRon** [comment]
I played a bit with the dark background for code - yet it looks "nice" for the code block itself, but it is - as you recognized - a bit too "harsh" contrast wise (you read first on white BG then the example on nearly-black).

You could have this "dark" as a kind of "code ruler" left side of such a code block - so people are more aware of what's placed there.
Or you add a line-number plugin like
https://github.com/wcoder/highlightjs-line-numbers.js/
and make it "automatically indented" by prepending such line numbers

phpdoc.org
![img](http://i.imgur.com/2Ghkrlm.png)

**Comment by GWRon** [comment]
Using some "margin-left" stuff and removing the internal paddings oft the "h4"-headlines (and its background of course) and some other small stuff:

![img](http://i.imgur.com/f02do68.png)
("Superstrict" shares CSS definition with the comment, would become another color of course)

**Comment by woollybah** [comment]
I think this is okay now.
